In [3]:
import numpy as np
import time
import sys

size = 100000000  


py_list = list(range(size))

# python list timing
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start:.6f} seconds")

# numpy array timing
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start:.6f} seconds")

# memory usage
print(f"python list approx size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array nbytes = {np_arr.nbytes} bytes")


python list time = 20.256887 seconds
numpy array time = 1.089610 seconds
python list approx size = 80000005600000000 bytes
numpy array nbytes = 800000000 bytes


In [4]:
# Creating NumPy Arrays from lists

arr = np.array([1, 2, 3, 4]) 
print(arr, type(arr)) 
arr2 = np.array([1, 2, 3, 4, "prime", 3.14]) 
print(arr2, type(arr2)) 



[1 2 3 4] <class 'numpy.ndarray'>
['1' '2' '3' '4' 'prime' '3.14'] <class 'numpy.ndarray'>


In [5]:
# 2D Arrays -Matrix 

arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3, arr3.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [18]:
arr1=np.zeros((2,3),dtype="int64") #prefill zeros
print(arr1,arr1.shape)


arr2= np.ones((5, )) #prefill ones
print(arr2,arr2.shape)

arr3=np.full((3,4), 100)#prefill with value
print(arr3,arr3.shape)

arr4=np.eye(3)#identity matrix
print(arr4,arr4.shape)

arr5=np.arange(1,11,2) #range elements
print(arr5,arr5.shape)


arr6=np.linspace(1,100,4) #evenly spaced array
print(arr6,arr6.shape)

arr6=np.linspace(1,100,3) #evenly spaced array
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)
[  1.   50.5 100. ] (3,)


In [20]:
#properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)


float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [22]:
#operations on array


arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)


#2D to 1D array
flattened=arr.flatten() 
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [40]:
#Indexing
arr=np.array([1,2,3,4,5,6])

print(arr[0])
print(arr[5])


arr=np.array([[1,2,3],[4,5,6]])

print(arr[0][1])
print(arr[1][2])


#fancy indexing

arr=np.array([1,2,3,4,5,6])

idx=[0,1,3]
print(arr[idx])


#boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
print(arr[arr<=3])
print(arr[arr % 2 ==0])


#slicing
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[1:])
print(arr[-1:])
print(arr[:-1])
print(arr[:-3])
print(arr[::2]) #to skip 2 elements
print(arr[::3])

1
6
2
6
[1 2 4]
[4 5]
[1 2 3]
[2 4]
[2 3 4]
[2 3 4 5 6]
[6]
[1 2 3 4 5]
[1 2 3]
[1 3 5]
[1 4]
