In [3]:
import numpy as np
import time
import sys

size = 100000000  


py_list = list(range(size))

# python list timing
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start:.6f} seconds")

# numpy array timing
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start:.6f} seconds")

# memory usage
print(f"python list approx size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array nbytes = {np_arr.nbytes} bytes")


python list time = 24.781256 seconds
numpy array time = 1.152618 seconds
python list approx size = 80000005600000000 bytes
numpy array nbytes = 800000000 bytes


In [4]:
# Creating NumPy Arrays from lists

arr = np.array([1, 2, 3, 4]) 
print(arr, type(arr)) 
arr2 = np.array([1, 2, 3, 4, "prime", 3.14]) 
print(arr2, type(arr2)) 



[1 2 3 4] <class 'numpy.ndarray'>
['1' '2' '3' '4' 'prime' '3.14'] <class 'numpy.ndarray'>


In [5]:
# 2D Arrays -Matrix 

arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3, arr3.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [18]:
arr1=np.zeros((2,3),dtype="int64") #prefill zeros
print(arr1,arr1.shape)


arr2= np.ones((5, )) #prefill ones
print(arr2,arr2.shape)

arr3=np.full((3,4), 100)#prefill with value
print(arr3,arr3.shape)

arr4=np.eye(3)#identity matrix
print(arr4,arr4.shape)

arr5=np.arange(1,11,2) #range elements
print(arr5,arr5.shape)


arr6=np.linspace(1,100,4) #evenly spaced array
print(arr6,arr6.shape)

arr6=np.linspace(1,100,3) #evenly spaced array
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)
[  1.   50.5 100. ] (3,)


In [20]:
#properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)


float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [22]:
#operations on array


arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)


#2D to 1D array
flattened=arr.flatten() 
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [40]:
#Indexing
arr=np.array([1,2,3,4,5,6])

print(arr[0])
print(arr[5])


arr=np.array([[1,2,3],[4,5,6]])

print(arr[0][1])
print(arr[1][2])


#fancy indexing

arr=np.array([1,2,3,4,5,6])

idx=[0,1,3]
print(arr[idx])


#boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
print(arr[arr<=3])
print(arr[arr % 2 ==0])


#slicing
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[1:])
print(arr[-1:])
print(arr[:-1])
print(arr[:-3])
print(arr[::2]) #to skip 2 elements
print(arr[::3])

1
6
2
6
[1 2 4]
[4 5]
[1 2 3]
[2 4]
[2 3 4]
[2 3 4 5 6]
[6]
[1 2 3 4 5]
[1 2 3]
[1 3 5]
[1 4]


In [4]:
#copy and of slice  compare


nums=[1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0]=200

print(sub_list)
print(nums)

arr = np.array([1,2,3,4,5])
sub_list = arr[1:3]
print(sub_list)
sub_list[0]=200

print(sub_list)
print(arr)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [6]:
#Data types in numpy array

arr=np.array([1,2,3,4,5])
print(arr,arr.dtype)

arr=np.array([1,2,3.0,4,5])
print(arr,arr.dtype)

[1 2 3 4 5] int64
[1. 2. 3. 4. 5.] float64


In [8]:
arr=np.array([1,2,3,4,"Pooja"])
print(arr,arr.dtype)

['1' '2' '3' '4' 'Pooja'] <U21


In [10]:
#complex numbers
arr1=np.array([3 + 5j])
arr2=np.array([2 + 3j])

print(arr1,arr1.dtype)
print(arr1+arr2)
print(arr1-arr2)

[3.+5.j] complex128
[5.+8.j]
[1.+2.j]


In [11]:
#objects
arr = np.array(["prime",{1,2,3},3.14])
print(arr,arr.dtype)

['prime' {1, 2, 3} 3.14] object


In [18]:
#Multidimensional arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_columns=np.sum(arr2D,axis=0)
print(sum_columns)

sum_rows=np.sum(arr2D,axis=1)
print(sum_rows)

#slice operation on 2D array

print(arr2D[0:2 , 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [31]:
#3D array operation


arr3D =np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])  #2 x 3 x 2
print(arr3D,arr3D.dtype,arr3D.shape)

#indexing

print(arr3D[1,2,0])
print("\n")
print(arr3D[0,1,0])

#slicing in 3D array
print(arr3D[:,0,:])   #here [which layer,which raw,which column] in this example : is used because to use both layer and both col and 0 is for accesing 0th row
print("\n")
print(arr3D[1,0:2,:])
print("\n")

#for replace the values by slicing
arr3D[:,0,:]=99 #first row from both layers
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] int64 (2, 3, 2)
11


3
[[1 2]
 [7 8]]


[[ 7  8]
 [ 9 10]]


[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [35]:
#vectarization 
arr=np.array([1,2,3,4,5])
arr1=np.array([7,7,8,9,15])
print(arr**2)
print(arr1+2)
print(arr+arr1)

[ 1  4  9 16 25]
[ 9  9 10 11 17]
[ 8  9 11 13 20]


In [38]:
#broadcasting (scaling array without extra memory)

arr1=np.array([1,2,3,4,5])
print(arr1,arr1.shape)
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2,arr2.shape)
print(arr1+arr2)

arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[6,7,8,9,10]])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1.shape)
print(arr2.shape)

print(arr1+arr2) ## gives error because the shapes are not compatible to add 

[1 2 3 4 5] (5,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
(3, 5)
(2, 5)


ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 

In [41]:
#vectorr normalization ( use of broadcasting)
#normalization means transforming its values so they fit in a specific scale or range

#1. Standard normalization    =   (arr-mean)/standard deviation    
    # standard deviation = square root of(sum(values-mean)^2 / total num of elements)



arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)

normalized_arr =(arr-mean) /std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [43]:
#Mathematical function in numpy
#aggregation
arr=np.array([1,2,3,4,5,6,7])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

28
5040
1
7
0
6
4.0
2.0
4.0
4.0


In [45]:
#power function
arr=np.array([1,2,3,4,5,6,7])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25 36 49]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]
[  1   8  27  64 125 216 343]


In [46]:
#log fuction
arr=np.array([1,2,3,4,5,6,7])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492]
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
  403.42879349 1096.63315843]


In [50]:
#rounding function

print(np.round(3.4)) #round near value
print(np.ceil(3.4)) #round up 
print(np.floor(3.4)) #round down
print(np.trunc(3.4)) #trucate the value

3.0
4.0
3.0
3.0


In [55]:
#unique function
arr=np.array([1,2,3,4,5,6,6,7,7])
print(np.unique(arr))
print(np.sort(arr))
arr=np.array([1,2,-3,4,5,6,6,7,7])
print(np.abs(arr)) #make -ve values to positive

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 6 7 7]
[1 2 3 4 5 6 6 7 7]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Vectorized operations
print(arr + 2)      # add scalar
print(arr * 3)      # multiply scalar
print(arr ** 2)     # square each element
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)


[3 4 5 6 7]
[ 3  6  9 12 15]
[ 1  4  9 16 25]
[5 7 9]
[ 4 10 18]
